INSERT into states values (1, 'SP');
INSERT into states values (2, 'PR');
INSERT into states values (3, 'SC');
INSERT into ddds values (1, '11', 1);
INSERT into ddds values (2, '12', 1);
INSERT into ddds values (3, '42', 2);
INSERT into ddds values (4, '43', 2);
INSERT into ddds values (5, '47', 3);
INSERT into ddds values (6, '48', 3);
INSERT into contacts values (1, 'fulano@gmail.com', 'Fulano', '9999-9999', 3);